cardinali=[


    {
        "nome": "Matteo Maria Zuppi",
        "dataNascita": "11/10/1955",
        "paese": "Italia",
        "ruolo": "Cardinale presbitero di Sant'Egidio, Arcivescovo metropolita di Bologna",
        "dataNomina": "05/10/2019",
        "continente": "Europa",
        "wikiUrl": "https://it.wikipedia.org/wiki/Matteo_Maria_Zuppi",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Matteo_Zuppi_2019.jpg/250px-Matteo_Zuppi_2019.jpg",
        "punteggio": 20
    },
    {
        "nome": "Pierbattista Pizzaballa",
        "dataNascita": "21/04/1965",
        "paese": "Italia",
        "ruolo": "Cardinale presbitero di Sant'Onofrio, Patriarca di Gerusalemme dei Latini",
        "dataNomina": "30/09/2023",
        "continente": "Asia",
        "wikiUrl": "https://it.wikipedia.org/wiki/Pierbattista_Pizzaballa",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Mons._Pierbattista_Pizzaballa.jpg/250px-Mons._Pierbattista_Pizzaballa.jpg",
        "punteggio": 19
    },
    {
        "nome": "Luis Antonio Tagle",
        "dataNascita": "21/06/1957",
        "paese": "Filippine",
        "ruolo": "Prefetto del Dicastero per l'Evangelizzazione",
        "dataNomina": "24/11/2012",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Cardinal_Luis_Antonio_Tagle_Sambuhay_2019.jpg/250px-Cardinal_Luis_Antonio_Tagle_Sambuhay_2019.jpg",
        "continente": "Asia",
        "wikiUrl": "https://it.wikipedia.org/wiki/Luis_Antonio_Tagle",
        "punteggio": 18
    },
    {
        "nome": "Pietro Parolin",
        "dataNascita": "17/01/1955",
        "paese": "Italia",
        "ruolo": "Cardinale vescovo dei Santi Simone e Giuda Taddeo a Torre Angela, Cardinale segretario di Stato",
        "dataNomina": "22/02/2014",
        "continente": "Europa",
        "wikiUrl": "https://it.wikipedia.org/wiki/Pietro_Parolin",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/In%C4%81ra_M%C5%ABrniece_tiekas_ar_Sv%C4%93t%C4%81_Kr%C4%93sla_Valsts_sekret%C4%81ru_%2826363562894%29-1%28cropped%29.jpg/250px-In%C4%81ra_M%C5%ABrniece_tiekas_ar_Sv%C4%93t%C4%81_Kr%C4%93sla_Valsts_sekret%C4%81ru_%2826363562894%29-1%28cropped%29.jpg",
        "punteggio": 17
    },
    {
        "nome": "Fridolin Ambongo Besungu",
        "dataNascita": "24/01/1960",
        "paese": "RD del Congo",
        "ruolo": "Cardinale presbitero di San Gabriele Arcangelo all'Acqua Traversa, Arcivescovo metropolita di Kinshasa",
        "dataNomina": "05/10/2019",
        "continente": "Africa",
        "wikiUrl": "https://it.wikipedia.org/wiki/Fridolin_Ambongo_Besungu",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/AED_11%C3%A8me_Nuit_des_T%C3%A9moins_-_Fridolin_Ambongo_-_2_%28cropped%29.jpg/250px-AED_11%C3%A8me_Nuit_des_T%C3%A9moins_-_Fridolin_Ambongo_-_2_%28cropped%29.jpg",
        "punteggio": 17
    },
    {
        "nome": "Jean-Claude Hollerich",
        "dataNascita": "09/08/1958",
        "paese": "Lussemburgo",
        "ruolo": "Cardinale presbitero di San Giovanni Crisostomo a Monte Sacro Alto, Arcivescovo di Lussemburgo",
        "dataNomina": "05/10/2019",
        "continente": "Europa",
        "wikiUrl": "https://it.wikipedia.org/wiki/Jean-Claude_Hollerich",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Jean-Claude_Hollerich.jpg/250px-Jean-Claude_Hollerich.jpg",
        "punteggio": 16
    },
    {
        "nome": "Péter Erdő",
        "dataNascita": "25/06/1952",
        "paese": "Ungheria",
        "ruolo": "Cardinale presbitero di Santa Maria Nuova, Arcivescovo metropolita di Esztergom-Budapest",
        "dataNomina": "21/10/2003",
        "continente": "Europa",
        "wikiUrl": "https://it.wikipedia.org/wiki/P%C3%A9ter_Erd%C5%91",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/P%C3%A9ter_Erd%C5%91_in_2011.jpg/250px-P%C3%A9ter_Erd%C5%91_in_2011.jpg",
        "punteggio": 14
    },
    {
        "nome": "Willem Jacobus Eĳk",
        "dataNascita": "22/06/1953",
        "paese": "Paesi Bassi",
        "ruolo": "Cardinale presbitero di San Callisto, Arcivescovo metropolita di Utrecht",
        "dataNomina": "18/02/2012",
        "continente": "Europa",
        "wikiUrl": "https://it.wikipedia.org/wiki/Willem_Jacobus_Eijk",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Willem_Eijk_%282020%29.jpg/250px-Willem_Eijk_%282020%29.jpg",
        "punteggio": 14
    },
    {
        "nome": "Peter Kodwo Appiah Turkson",
        "dataNascita": "11/10/1948",
        "paese": "Ghana",
        "ruolo": "Cardinale presbitero di San Liborio, Cancelliere della Pontificia accademia delle scienze e della Pontificia accademia delle scienze sociali",
        "dataNomina": "21/10/2003",
        "continente": "Africa",
        "wikiUrl": "https://it.wikipedia.org/wiki/Peter_Kodwo_Appiah_Turkson",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Peter_Turkson_%28cropped%29.jpg/250px-Peter_Turkson_%28cropped%29.jpg",
        "punteggio": 13
    },
    {
        "nome": "Carlos Aguiar Retes",
        "dataNascita": "09/01/1950",
        "paese": "Messico",
        "ruolo": "Cardinale presbitero dei Santi Fabiano e Venanzio a Villa Fiorelli, Arcivescovo metropolita di Città del Messico",
        "dataNomina": "19/11/2016",
        "continente": "America del Nord",
        "wikiUrl": "https://it.wikipedia.org/wiki/Carlos_Aguiar_Retes",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Cardenalaguiar.jpg/330px-Cardenalaguiar.jpg",
        "punteggio": 13
    },
    {
        "nome": "George Jacob Koovakad",
        "dataNascita": "11/08/1973",
        "paese": "India",
        "ruolo": "Cardinale diacono di Sant'Antonio di Padova a Circonvallazione Appia, Prefetto del Dicastero per il dialogo interreligioso e organizzatore dei viaggi papali",
        "dataNomina": "07/12/2024",
        "continente": "Asia",
        "wikiUrl": "https://it.wikipedia.org/wiki/George_Jacob_Koovakad",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Card._George_J._Koovakad.jpg/250px-Card._George_J._Koovakad.jpg",
        "punteggio": 12
    },
    {
        "nome": "Dominique Mamberti",
        "dataNascita": "07/03/1952",
        "paese": "Francia",
        "ruolo": "Cardinale diacono di Santo Spirito in Sassia, Prefetto del Supremo tribunale della Segnatura apostolica e Cardinale protodiacono",
        "dataNomina": "14/02/2015",
        "continente": "Europa",
        "wikiUrl": "https://it.wikipedia.org/wiki/Dominique_Mamberti",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Dominique_Mamberti%2C_14_Dec_2010.jpg/250px-Dominique_Mamberti%2C_14_Dec_2010.jpg",
        "punteggio": 12
    },
    {
        "nome": "Blase Joseph Cupich",
        "dataNascita": "19/03/1949",
        "paese": "Stati Uniti",
        "ruolo": "Cardinale presbitero di San Bartolomeo all'Isola, Arcivescovo metropolita di Chicago",
        "dataNomina": "19/11/2016",
        "continente": "America del Nord",
        "wikiUrl": "https://it.wikipedia.org/wiki/Blase_Joseph_Cupich",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Cdl._Cupich_%28cropped%29.png/250px-Cdl._Cupich_%28cropped%29.png",
        "punteggio": 11
    },
    {
        "nome": "Baldassare Reina",
        "dataNascita": "26/11/1970",
        "paese": "Italia",
        "ruolo": "Cardinale presbitero di Santa Maria Assunta e San Giuseppe a Primavalle, Vicario generale per la diocesi di Roma e arciprete della basilica di San Giovanni in Laterano",
        "dataNomina": "07/12/2024",
        "continente": "Europa",
        "wikiUrl": "https://it.wikipedia.org/wiki/Baldassare_Reina",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Baldassare_Reina.jpg/330px-Baldassare_Reina.jpg",
        "punteggio": 11
    },
    {
        "nome": "Anders Arborelius",
        "dataNascita": "24/09/1949",
        "paese": "Svezia",
        "ruolo": "Cardinale presbitero di Santa Maria degli Angeli, Vescovo di Stoccolma",
        "dataNomina": "28/06/2017",
        "continente": "Europa",
        "wikiUrl": "https://it.wikipedia.org/wiki/Anders_Arborelius",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Anders_Arborelius_in_2019.jpg/250px-Anders_Arborelius_in_2019.jpg",
        "punteggio": 11
    },
    {
        "nome": "Charles Maung Bo",
        "dataNascita": "29/10/1948",
        "paese": "Birmania",
        "ruolo": "Cardinale presbitero di Sant'Ireneo a Centocelle, Arcivescovo metropolita di Yangon",
        "dataNomina": "14/02/2015",
        "continente": "Asia",
        "wikiUrl": "https://it.wikipedia.org/wiki/Charles_Maung_Bo",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Maung_Bo.jpg/330px-Maung_Bo.jpg",
        "punteggio": 10
    },
    {
        "nome": "Albert Malcolm Ranjith Patabendige Don",
        "dataNascita": "15/11/1947",
        "paese": "Sri Lanka",
        "ruolo": "Cardinale presbitero di San Lorenzo in Lucina, Arcivescovo metropolita di Colombo",
        "dataNomina": "20/11/2010",
        "continente": "Asia",
        "wikiUrl": "https://it.wikipedia.org/wiki/Albert_Malcolm_Ranjith_Patabendige_Don",
        "imageUrl": "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRyYhpn3XPrr-jaebDKuGRC6YcN6TClYt-QzlXbyTRuoXxpDfQD0s_Bcf7TXFRCQl8_-Fiex3q6HWrj73LH7UyaLA",
        "punteggio": 9
    },
    {
        "nome": "Wilton Daniel Gregory",
        "dataNascita": "07/12/1947",
        "paese": "Stati Uniti",
        "ruolo": "Cardinale presbitero dell'Immacolata Concezione di Maria a Grottarossa, Arcivescovo emerito di Washington",
        "dataNomina": "28/11/2020",
        "continente": "America del Nord",
        "wikiUrl": "https://it.wikipedia.org/wiki/Wilton_Daniel_Gregory",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Cardinal_Wilton_Daniel_Gregory_in_2024_%28cropped%29.jpg/250px-Cardinal_Wilton_Daniel_Gregory_in_2024_%28cropped%29.jpg",
        "punteggio": 9
    },
    {
        "nome": "Giuseppe Betori",
        "dataNascita": "25/02/1947",
        "paese": "Italia",
        "ruolo": "Cardinale presbitero di San Marcello, Arcivescovo emerito di Firenze",
        "dataNomina": "18/02/2012",
        "continente": "Europa",
        "wikiUrl": "https://it.wikipedia.org/wiki/Giuseppe_Betori",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Betori.JPG/250px-Betori.JPG",
        "punteggio": 8
    },
    {
        "nome": "Fernando Vérgez Alzaga",
        "dataNascita": "01/03/1945",
        "paese": "Spagna",
        "ruolo": "Cardinale diacono di Santa Maria della Mercede e Sant'Adriano a Villa Albani",
        "dataNomina": "27/08/2022",
        "continente": "Europa",
        "wikiUrl": "https://it.wikipedia.org/wiki/Fernando_V%C3%A9rgez_Alzaga",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Fernando_V%C3%A9rgez_Alzaga%2C_posesi%C3%B3n_Cobo-Roma.jpg/500px-Fernando_V%C3%A9rgez_Alzaga%2C_posesi%C3%B3n_Cobo-Roma.jpg",
        "punteggio": 7
    },
    {
        "nome": "Mario Grech",
        "dataNascita": "20/02/1957",
        "paese": "Malta",
        "ruolo": "Cardinale diacono dei Santi Cosma e Damiano, Segretario generale del Sinodo dei Vescovi",
        "dataNomina": "28/11/2020",
        "continente": "Europa",
        "wikiUrl": "https://it.wikipedia.org/wiki/Mario_Grech",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Cardinal_Mario_Grech.jpg/250px-Cardinal_Mario_Grech.jpg",
        "punteggio": 7
    },
    {
        "nome": "Robert Francis Prevost",
        "dataNascita": "14/09/1955",
        "paese": "Stati Uniti",
        "ruolo": "Cardinale vescovo di Albano, Prefetto del Dicastero per i vescovi",
        "dataNomina": "30/09/2023",
        "continente": "America del Nord",
        "wikiUrl": "https://it.wikipedia.org/wiki/Robert_Francis_Prevost",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Mons._Robert_Prevost%2C_OSA_%28cropped%29.jpg/250px-Mons._Robert_Prevost%2C_OSA_%28cropped%29.jpg",
        "punteggio": 7
    },
    {
        "nome": "Ángel Fernández Artime",
        "dataNascita": "21/08/1960",
        "paese": "Spagna",
        "ruolo": "Cardinale diacono di Santa Maria Ausiliatrice in Via Tuscolana, Pro-prefetto del Dicastero per gli Istituti di Vita Consacrata e le Società di Vita Apostolica",
        "dataNomina": "30/09/2023",
        "continente": "Europa",
        "wikiUrl": "https://it.wikipedia.org/wiki/%C3%81ngel_Fern%C3%A1ndez_Artime",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/%C3%81ngel_Fern%C3%A1ndez_Artime_%281960-%29%2C.jpg/250px-%C3%81ngel_Fern%C3%A1ndez_Artime_%281960-%29%2C.jpg",
        "punteggio": 8
    },
    {
        "nome": "Robert Sarah",
        "dataNascita": "15/06/1945",
        "paese": "Guinea",
        "ruolo": "Cardinale presbitero pro hac vice di San Giovanni Bosco in via Tuscolana, Prefetto emerito della Congregazione per il culto divino e la disciplina dei sacramenti",
        "dataNomina": "20/11/2010",
        "continente": "Africa",
        "wikiUrl": "https://it.wikipedia.org/wiki/Robert_Sarah",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Cardinal_Robert_Sarah_%28cropped%29.JPG/250px-Cardinal_Robert_Sarah_%28cropped%29.JPG",
        "punteggio": 7

    },
    {
        "nome": "Jean-Marc Aveline",
        "dataNascita": "26/12/1958",
        "paese": "Francia",
        "ruolo": "Cardinale presbitero di Santa Maria ai Monti, Arcivescovo metropolita di Marsiglia",
        "dataNomina": "27/08/2022",
        "continente": "Europa",
        "wikiUrl": "https://it.wikipedia.org/wiki/Jean-Marc_Aveline",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Mgr_Jean-Marc_Aveline_par_Claude_Truong-Ngoc_juillet_2021.jpg/500px-Mgr_Jean-Marc_Aveline_par_Claude_Truong-Ngoc_juillet_2021.jpg",
        "punteggio": 7
    },
    {
        "nome": "Daniel Fernando Sturla Berhouet",
        "dataNascita": "04/07/1959",
        "paese": "Uruguay",
        "ruolo": "Cardinale presbitero di Santa Galla, Arcivescovo metropolita di Montevideo",
        "dataNomina": "14/02/2015",
        "continente": "America del Sud",
        "wikiUrl": "https://it.wikipedia.org/wiki/Daniel_Fernando_Sturla_Berhouet",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Daniel_Sturla_en_Misa_0013.jpg/330px-Daniel_Sturla_en_Misa_0013.jpg",
        "punteggio": 7
    },
    {
        "nome": "Thomas Aquino Manyo Maeda",
        "dataNascita": "03/03/1949",
        "paese": "Giappone",
        "ruolo": "Cardinale presbitero di Santa Pudenziana, Arcivescovo metropolita di Osaka-Takamatsu",
        "dataNomina": "28/06/2018",
        "continente": "Asia",
        "wikiUrl": "https://it.wikipedia.org/wiki/Thomas_Aquino_Manyo_Maeda",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Archbishop_Thomas_Aquinas_Manyo_Maeda_in_2015.jpg/225px-Archbishop_Thomas_Aquinas_Manyo_Maeda_in_2015.jpg",
        "punteggio": 7
    },
    {
        "nome": "Leonardo Ulrich Steiner",
        "dataNascita": "06/11/1950",
        "paese": "Brasile",
        "ruolo": "Cardinale presbitero di San Leonardo da Porto Maurizio ad Acilia, Arcivescovo metropolita di Manaus",
        "dataNomina": "27/08/2022",
        "continente": "America del Sud",
        "wikiUrl": "https://it.wikipedia.org/wiki/Leonardo_Ulrich_Steiner",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/CDH_-_Comiss%C3%A3o_de_Direitos_Humanos_e_Legisla%C3%A7%C3%A3o_Participativa_%2821412066008%29.jpg/250px-CDH_-_Comiss%C3%A3o_de_Direitos_Humanos_e_Legisla%C3%A7%C3%A3o_Participativa_%2821412066008%29.jpg",
        "punteggio": 7
    },
    {
        "nome": "Gerhard Ludwig Müller",
        "dataNascita": "31/12/1947",
        "paese": "Germania",
        "ruolo": "Cardinale presbitero pro hac vice di Sant'Agnese in Agone, Prefetto emerito della Congregazione per la dottrina della fede",
        "dataNomina": "22/02/2014",
        "continente": "Europa",
        "wikiUrl": "https://it.wikipedia.org/wiki/Gerhard_Ludwig_M%C3%BCller",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/HY_Gerhard_Ludwig_M%C3%BCller.png/250px-HY_Gerhard_Ludwig_M%C3%BCller.png",
        "punteggio": 7

    },
    {
        "nome": "Mykola Byčok",
        "dataNascita": "13/02/1980",
        "paese": "Ucraina",
        "ruolo": "Cardinale presbitero di Santa Sofia a Via Boccea, Eparca dei Santi Pietro e Paolo di Melbourne degli ucraini",
        "dataNomina": "07/12/2024",
        "continente": "Europa",
        "wikiUrl": "https://it.wikipedia.org/wiki/Mykola_By%C4%8Dok",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Mykola_Bychok%2C_CSsR.jpg/330px-Mykola_Bychok%2C_CSsR.jpg",
        "punteggio": 7
    },
    {
        "nome": "Giorgio Marengo",
        "dataNascita": "07/06/1974",
        "paese": "Italia",
        "ruolo": "Cardinale presbitero di San Giuda Taddeo Apostolo, Prefetto apostolico di Ulan Bator",
        "dataNomina": "27/08/2022",
        "continente": "Asia",
        "wikiUrl": "https://it.wikipedia.org/wiki/Giorgio_Marengo",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/1/10/Cardeal_marengo.jpg",
        "punteggio": 7
    },
    {
        "nome": "Raymond Leo Burke",
        "dataNascita": "30/06/1948",
        "paese": "Stati Uniti",
        "ruolo": "Cardinale presbitero pro hac vice di Sant'Agata dei Goti, Patrono emerito del Sovrano Militare Ordine di Malta",
        "dataNomina": "20/11/2010",
        "continente": "Europa",
        "wikiUrl": "https://it.wikipedia.org/wiki/Raymond_Leo_Burke",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Raymond_Leo_Cardinal_Burke.JPG/250px-Raymond_Leo_Cardinal_Burke.JPG",
        "punteggio": 7
    },
    {
        "nome": "Domenico Battaglia",
        "dataNascita": "20/01/1963",
        "paese": "Italia",
        "ruolo": "Cardinale presbitero di San Marco in Agro Laurentino, Arcivescovo metropolita di Napoli",
        "dataNomina": "07/12/2024",
        "continente": "Europa",
        "wikiUrl": "https://it.wikipedia.org/wiki/Domenico_Battaglia",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/8/8b/Don_Mimmo_Battaglia_pentecoste_2018_%28cropped%29.jpg",
        "punteggio": 7
    },
    {
        "nome": "Joseph William Tobin",
        "dataNascita": "03/05/1952",
        "paese": "Stati Uniti",
        "ruolo": "Cardinale presbitero di Santa Maria delle Grazie a Via Trionfale, Arcivescovo metropolita di Newark",
        "dataNomina": "19/11/2016",
        "continente": "America del Nord",
        "wikiUrl": "https://it.wikipedia.org/wiki/Joseph_William_Tobin",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Cardinal_Tobin_%28cropped%29.jpg/250px-Cardinal_Tobin_%28cropped%29.jpg",
        "punteggio": 7

    },
    {
        "nome": "Roberto Repole",
        "dataNascita": "29/01/1967",
        "paese": "Italia",
        "ruolo": "Cardinale presbitero di Gesù Divin Maestro alla Pineta Sacchetti, Arcivescovo metropolita di Torino e Vescovo di Susa",
        "dataNomina": "07/12/2024",
        "continente": "Europa",
        "wikiUrl": "https://it.wikipedia.org/wiki/Roberto_Repole",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Roberto_Repole.jpg/250px-Roberto_Repole.jpg",
        "punteggio": 7
    },
    {
        "nome": "Timothy Radcliffe",
        "dataNascita": "22/08/1945",
        "paese": "Regno Unito",
        "ruolo": "Cardinale diacono dei Santissimi Nomi di Gesù e Maria in via Lata, Già Maestro generale dell'Ordine dei predicatori",
        "dataNomina": "07/12/2024",
        "continente": "Europa",
        "wikiUrl": "https://it.wikipedia.org/wiki/Timothy_Radcliffe",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/2025.02.22._Timothy_Radcliffe_OP_Warsaw_Poland_Photo_Mariusz_Kubik_01.JPG/250px-2025.02.22._Timothy_Radcliffe_OP_Warsaw_Poland_Photo_Mariusz_Kubik_01.JPG",
        "punteggio": 7
    },
    {
        "nome": "Kevin Joseph Farrell",
        "dataNascita": "02/09/1947",
        "paese": "Stati Uniti",
        "ruolo": "Cardinale diacono di San Giuliano Martire, Prefetto del Dicastero per i laici, la famiglia e la vita, Camerlengo di Santa Romana Chiesa e presidente della Commissione di materie riservate",
        "dataNomina": "19/11/2016",
        "continente": "America del Nord",
        "wikiUrl": "https://it.wikipedia.org/wiki/Kevin_Joseph_Farrell",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Kevin_Joseph_Farrell_1.jpg/330px-Kevin_Joseph_Farrell_1.jpg",
        "punteggio": 7
    },
    {
        "nome": "Fabio Baggio",
        "dataNascita": "15/01/1965",
        "paese": "Italia",
        "ruolo": "Cardinale diacono di San Filippo Neri in Eurosia, Sottosegretario del Dicastero per il servizio dello sviluppo umano integrale",
        "dataNomina": "07/12/2024",
        "continente": "Europa",
        "wikiUrl": "https://it.wikipedia.org/wiki/Fabio_Baggio",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Fabio_Baggio-5-2-2019.jpg/330px-Fabio_Baggio-5-2-2019.jpg",
        "punteggio": 7
    },

]